name: anti-immigrant-sentiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - beautifulsoup4=4.9.*
  - matplotlib=3.3.*
  - numpy=1.19.*
  - pandas=1.2.*
  - pip # use latest
  - jupyter # use latest, only necessary for interactive use
  - pip:
    - chromedriver-binary
    - selenium==4.1.3

