name: anti-immigrant-sentiment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyter # use latest, for interactive use
  - pylint # use latest, for interactive use
  - colorama=0.4.*
  - beautifulsoup4=4.9.*
  - make=4.*
  - matplotlib=3.3.*
  - numpy=1.19.*
  - pandas=1.4.2
  - pyarrow=7.0.0
  - firefox=99.0.*
  - pip # use latest
  - pip:
    - webdriver-manager==3.5.4
    - selenium==4.1.3
